version: '3'

vars:
  BINARY: bonsai
  CMD: ./cmd/bonsai
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo dev
  LDFLAGS: -s -w -X github.com/pithecene-io/bonsai/internal/cli.Version={{.VERSION}}

tasks:
  default:
    desc: Build and test
    cmds:
      - task: build
      - task: test

  build:
    desc: Build the bonsai binary
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o {{.BINARY}} {{.CMD}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY}}"

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  fmt:
    desc: Run gofmt
    cmds:
      - gofmt -w .

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY}}

  check:
    desc: Run all checks (vet, lint, test)
    cmds:
      - task: vet
      - task: lint
      - task: test

  snapshot:
    desc: Build release snapshot (local test)
    cmds:
      - goreleaser build --snapshot --clean
